apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  namespace: default
  labels:
    app: nodejs
spec:
  containers:
    - name: nodejs-container
      image: mycontainerregistryoct2.azurecr.io/nodejs-work:latest
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: mycontainerregistryoct2
